apiVersion: v1
kind: Pod
metadata:
  name: init-pod
spec:
  volumes:
  - name: sharedvol
    emptyDir: {}
  initContainers:
    - name: download
      image: alpine:3.22.2
      command: ['sh', '-c', 'sleep 30; apk update; apk add git; mkdir /app; git clone -b develop https://github.com/mariano-italiano/lx-k_Nov.git /app/']
      volumeMounts:
      - name: sharedvol
        mountPath: /app
  containers:
    - name: nginx
      image: nginx:1.14.2
      volumeMounts: 
      - name: sharedvol
        mountPath: /usr/share/nginx/html

