apiVersion: v1
kind: Pod
metadata:
  name: sidecar-pod
spec:
  containers:
  - name: busybox1
    image: busybox
    command: ['sh', '-c', 'while true; do echo my apps logs >> /output/app.log; sleep 10s ; done']
    volumeMounts:
    - name: sharedvol
      mountPath: /output
  - name: sidecar 
    image: busybox
    command: ['sh', '-c', 'tail -f /input/app.log']
    volumeMounts:
    - name: sharedvol
      mountPath: /input
  volumes:
  - name: sharedvol
    emptyDir: {}

