apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: test-httpd
  name: test-httpd
spec:
  containers:
  - image: httpd
    name: test-httpd
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
