apiVersion: batch/v1
kind: Job
metadata:
  name: job-sleep
spec:
  completions: 3
  template:
    spec:
      containers:
      - name: delay
        image: busybox
        command: ['/bin/sleep']
        args: ["15"]
      restartPolicy: Never
